if(DEFINED POLLY_FLAGS_IOS_NOCODESIGN_SDK13_CMAKE_)
  return()
else()
  set(POLLY_FLAGS_IOS_NOCODESIGN_SDK13_CMAKE_ 1)
endif()

set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED NO)
